blog:
  pattern: /blog
  defaults: { _controller: WhitewashingBlogBundle:Blog:index }

blog_admin_dashboard:
  pattern: /blog/admin
  defaults: { _controller: WhitewashingBlogBundle:AdminPost:index }

blog_admin_list_authors:
  pattern: /blog/admin/list/authors
  defaults: { _controller: WhitewashingBlogBundle:Author:list }

blog_admin_new_author:
  pattern: /blog/admin/new/author
  defaults: { _controller: WhitewashingBlogBundle:Author:new }

blog_show_tag:
  pattern: /blog/tag/{tagName}
  defaults: { _controller: WhitewashingBlogBundle:Blog:tag }

blog_feed:
  pattern: /blog/feed
  defaults: { _controller: WhitewashingBlogBundle:Feed:index }

blog_feed_tags:
  pattern: /blog/tag/{tagName}/feed
  defaults: { _controller: WhitewashingBlogBundle:Feed:tag }

blog_feed_category:
  pattern: /blog/category/{categoryShort}/feed
  defaults: { _controller: WhitewashingBlogBundle:Feed:category }

blog_post_new:
  pattern: /blog/admin/posts/new
  defaults: { _controller: WhitewashingBlogBundle:AdminPost:new }

blog_post_edit:
  pattern: /blog/admin/posts/{id}/edit
  defaults: { _controller: WhitewashingBlogBundle:AdminPost:edit }

blog_post_delete:
  pattern: /blog/admin/posts/{id}/delete
  defaults: { _controller: WhitewashingBlogBundle:AdminPost:delete }

blog_post_admin:
  pattern: /blog/admin/posts/manage
  defaults: { _controller: WhitewashingBlogBundle:AdminPost:manage }

blog_show_post:
  pattern: /blog/{id}
  defaults: { _controller: WhitewashingBlogBundle:Blog:view }

blog_tags:
  pattern: /blog/list/tags
  defaults: { _controller: WhitewashingBlogBundle:Blog:listTags }
